/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelpWnd.java
 *
 * Created on Apr 15, 2014, 10:19:12 PM
 */
package net.jeffreysanti.text_analy4;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.WindowConstants;

/**
 *
 * @author jeffrey
 */
public class HelpWnd extends javax.swing.JFrame {

    /** Creates new form HelpWnd */
    public HelpWnd(HashMap<String, HashSet<String>> doc) {
        initComponents();
        
        this.setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);
        this.lstPages.setModel(new DefaultListModel());
        
        D = doc;
        curPg = "index";
        try {
            switchPage();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HelpWnd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HelpWnd.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void switchPage() throws FileNotFoundException, IOException
    {
        this.lblPage.setText(curPg);
        
        String txt = "";
        File f = new File("RCode/doc/"+curPg+".txt");
        BufferedReader reader = new BufferedReader(new FileReader(f));
        String line=null;
        while((line=reader.readLine()) != null){
            txt += line +"\n";
        }
        this.txtArea.setText(txt);
        
        ((DefaultListModel)this.lstPages.getModel()).clear();
        for(String s : D.get(curPg)){
            ((DefaultListModel)this.lstPages.getModel()).addElement(s);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPages = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        lblPage.setText("jLabel1");
        getContentPane().add(lblPage);

        txtArea.setColumns(20);
        txtArea.setEditable(false);
        txtArea.setRows(5);
        txtArea.setMaximumSize(new java.awt.Dimension(10000, 300));
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1);

        lstPages.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPagesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPages);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void lstPagesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPagesValueChanged
    if(lstPages.getSelectedIndex() >= 0 && lstPages.getSelectedIndex() < this.lstPages.getModel().getSize()){
            try {
                curPg = (String) ((DefaultListModel)this.lstPages.getModel()).getElementAt(evt.getFirstIndex());
                this.lstPages.setSelectedIndices(new int[] {});
                switchPage();
            } catch (Exception ex) {
                Logger.getLogger(HelpWnd.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
}//GEN-LAST:event_lstPagesValueChanged

    /**
     * @param args the command line arguments
     */
    
    private HashMap<String, HashSet<String>> D;
    private String curPg;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPage;
    private javax.swing.JList lstPages;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
